---
- name: Copy my SSH key
  authorized_key:
    user: "{{ ansible_user }}"
    key:  "https://github.com/ctxzz.keys"

- name: apt-get update
  become: True
  apt:
    update_cache: yes
    cache_valid_time: 86400 # once a day

- name: Make sure locale is present
  become: True
  locale_gen:
    name: ja_JP.UTF-8

- name: set timezone
  become: True
  timezone:
    name: Asia/Tokyo

- name: Install common packages
  become: True
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - bundler
    - git
    - ruby
    - vim
    - wget
    - influxdb-client

- include: configurations.yml
- include: python.yml
