---
- name: Install serveral python libraries and tools
  become: True
  apt:
    name: "{{ item }}"
  with_items:
    - libboost-python-dev # for RF24 python library
    - python-dev
    - python-pip
    - python3-pip
    - python-setuptools

- name: Main playbook | update pip
  pip: name=pip executable=pip extra_args='--upgrade'

- name: Main playbook | update pip3
  pip: name=pip executable=pip3 extra_args='--upgrade'

- name: Main playbook | install python3 modules globally
  pip: name=pylint executable=pip3

- name: pip install
  pip:
    name:
      - influxdb-client
      - numpy
#      - grovepi
